[2025-04-12T16:04:01.803544+02:00] app.ERROR: Server Error: Database connection failed during controller resolution {"uri":"/uptaeb-mvc/login","class":"App\\Controllers\\AuthController","method":null,"exception_message":"No se pudo conectar a la base de datos.","exception_trace":"#0 C:\\xampp\\htdocs\\uptaeb-mvc\\app\\Core\\Application.php(174): App\\Core\\Database::getInstance()\n#1 C:\\xampp\\htdocs\\uptaeb-mvc\\app\\Core\\Application.php(146): App\\Core\\Application->resolveController('App\\\\Controllers...')\n#2 C:\\xampp\\htdocs\\uptaeb-mvc\\app\\Core\\Application.php(115): App\\Core\\Application->handleFoundRoute(Array, Array)\n#3 C:\\xampp\\htdocs\\uptaeb-mvc\\app\\Core\\Application.php(99): App\\Core\\Application->handleRoute(Array)\n#4 C:\\xampp\\htdocs\\uptaeb-mvc\\public\\index.php(23): App\\Core\\Application->run()\n#5 {main}"} []
[2025-04-12T16:04:02.361696+02:00] app.ERROR: Server Error: Database connection failed during controller resolution {"uri":"/uptaeb-mvc/login","class":"App\\Controllers\\AuthController","method":null,"exception_message":"No se pudo conectar a la base de datos.","exception_trace":"#0 C:\\xampp\\htdocs\\uptaeb-mvc\\app\\Core\\Application.php(174): App\\Core\\Database::getInstance()\n#1 C:\\xampp\\htdocs\\uptaeb-mvc\\app\\Core\\Application.php(146): App\\Core\\Application->resolveController('App\\\\Controllers...')\n#2 C:\\xampp\\htdocs\\uptaeb-mvc\\app\\Core\\Application.php(115): App\\Core\\Application->handleFoundRoute(Array, Array)\n#3 C:\\xampp\\htdocs\\uptaeb-mvc\\app\\Core\\Application.php(99): App\\Core\\Application->handleRoute(Array)\n#4 C:\\xampp\\htdocs\\uptaeb-mvc\\public\\index.php(23): App\\Core\\Application->run()\n#5 {main}"} []
[2025-04-12T16:16:42.976452+02:00] app.ERROR: Server Error: Controller instantiation failed {"uri":"/uptaeb-mvc/admin/users","class":"App\\Controllers\\Admin\\UserController","method":null,"exception_message":"Too few arguments to function App\\Controllers\\Admin\\UserController::__construct(), 1 passed in C:\\xampp\\htdocs\\uptaeb-mvc\\app\\Core\\Application.php on line 178 and exactly 2 expected","exception_trace":"#0 C:\\xampp\\htdocs\\uptaeb-mvc\\app\\Core\\Application.php(178): App\\Controllers\\Admin\\UserController->__construct(Object(App\\Models\\UserModel))\n#1 C:\\xampp\\htdocs\\uptaeb-mvc\\app\\Core\\Application.php(146): App\\Core\\Application->resolveController('App\\\\Controllers...')\n#2 C:\\xampp\\htdocs\\uptaeb-mvc\\app\\Core\\Application.php(115): App\\Core\\Application->handleFoundRoute(Array, Array)\n#3 C:\\xampp\\htdocs\\uptaeb-mvc\\app\\Core\\Application.php(99): App\\Core\\Application->handleRoute(Array)\n#4 C:\\xampp\\htdocs\\uptaeb-mvc\\public\\index.php(23): App\\Core\\Application->run()\n#5 {main}"} []
[2025-04-12T16:20:02.798306+02:00] app.ERROR: Error en UserModel::findUserByEmail {"email":"yerbamala12@gmail.com","exception":"[object] (PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'uptaeb_mvc.users' doesn't exist at C:\\xampp\\htdocs\\uptaeb-mvc\\app\\Models\\UserModel.php:67)"} []
[2025-04-12T16:22:00.712471+02:00] app.ERROR: Error en UserModel::getAllUsers {"exception":"[object] (PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'uptaeb_mvc.users' doesn't exist at C:\\xampp\\htdocs\\uptaeb-mvc\\app\\Models\\UserModel.php:30)"} []
[2025-04-12T16:22:44.295658+02:00] app.ERROR: Error en UserModel::getAllUsers {"exception":"[object] (PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'uptaeb_mvc.users' doesn't exist at C:\\xampp\\htdocs\\uptaeb-mvc\\app\\Models\\UserModel.php:30)"} []
